-- MySQL Script generated by MySQL Workbench
-- Thu Jun 18 15:57:28 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema db_projectone
-- -----------------------------------------------------
-- Inicialização da integração entre o backend e o banco de dados.

-- -----------------------------------------------------
-- Schema db_projectone
--
-- Inicialização da integração entre o backend e o banco de dados.
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `db_projectone` DEFAULT CHARACTER SET utf8 ;
USE `db_projectone` ;

-- -----------------------------------------------------
-- Table `db_projectone`.`usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_projectone`.`usuarios` (
  `id` SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `usuario` VARCHAR(12) NOT NULL,
  `senha` CHAR(32) NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  `permissao` TINYINT(1) UNSIGNED NOT NULL,
  `ativo` TINYINT(1) UNSIGNED NOT NULL COMMENT '0 - ATIVO\n1 - INATIVO',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `usuario_UNIQUE` (`usuario` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_projectone`.`categorias`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_projectone`.`categorias` (
  `id` TINYINT UNSIGNED ZEROFILL NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(30) NOT NULL,
  `descricao` VARCHAR(100) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_projectone`.`produtos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_projectone`.`produtos` (
  `codigo` SMALLINT UNSIGNED ZEROFILL NOT NULL AUTO_INCREMENT,
  `modelo` VARCHAR(30) NOT NULL,
  `valor` DECIMAL(7,2) UNSIGNED NOT NULL,
  `descricao` TEXT NULL,
  `categorias_id` TINYINT UNSIGNED ZEROFILL NOT NULL,
  PRIMARY KEY (`codigo`),
  INDEX `fk_produtos_categorias_idx` (`categorias_id` ASC),
  CONSTRAINT `fk_produtos_categorias`
    FOREIGN KEY (`categorias_id`)
    REFERENCES `db_projectone`.`categorias` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
