-- MySQL Script generated by MySQL Workbench
-- qua 17 fev 2021 11:00:48
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema db_projectone
-- -----------------------------------------------------
-- Inicialização da integração entre o backend e o banco de dados.

-- -----------------------------------------------------
-- Schema db_projectone
--
-- Inicialização da integração entre o backend e o banco de dados.
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `db_projectone` DEFAULT CHARACTER SET utf8 ;
USE `db_projectone` ;

-- -----------------------------------------------------
-- Table `db_projectone`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_projectone`.`users` (
  `id` SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(12) NOT NULL,
  `password` CHAR(32) NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  `permission` TINYINT(1) UNSIGNED NOT NULL,
  `active` TINYINT(1) UNSIGNED NOT NULL COMMENT '0 - ATIVO\n1 - INATIVO',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `usuario_UNIQUE` (`username` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_projectone`.`categories`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_projectone`.`categories` (
  `id` TINYINT UNSIGNED ZEROFILL NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(30) NOT NULL,
  `description` VARCHAR(100) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_projectone`.`products`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_projectone`.`products` (
  `code` SMALLINT UNSIGNED ZEROFILL NOT NULL AUTO_INCREMENT,
  `model` VARCHAR(30) NOT NULL,
  `value` DECIMAL(7,2) UNSIGNED NOT NULL,
  `description` TEXT NULL,
  `categories_id` TINYINT UNSIGNED ZEROFILL NOT NULL,
  PRIMARY KEY (`code`, `categories_id`),
  INDEX `fk_products_categories_idx` (`categories_id` ASC),
  CONSTRAINT `fk_products_categories`
    FOREIGN KEY (`categories_id`)
    REFERENCES `db_projectone`.`categories` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
